# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

EM_loop <- function(start, lib_mat, m, mu, sigma, isigma, iOsigO, S, O_list, Y, z, O_mat, pi_g, d, N, G) {
    .Call(`_DangLoop_EM_loop`, start, lib_mat, m, mu, sigma, isigma, iOsigO, S, O_list, Y, z, O_mat, pi_g, d, N, G)
}

rcpparma_hello_world <- function() {
    .Call(`_DangLoop_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_DangLoop_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_DangLoop_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_DangLoop_rcpparma_bothproducts`, x)
}

